### PR TITLE
Version 0.2

### PR DESCRIPTION
**Pull request by cberube**
To test:
* Review code and test coverage

### CODE REVIEW

**Comment by nackjicholson** [comment]
Do you want to put doc blocks on the `class`'s and methods just in case we want to put em through an auto doc generation tool.

I'm kind of indifferent about it honestly. Code is pretty well commented and clear.

**Comment by cberube** [comment]
@nackjicholson -- Docs are good.

**Comment by nackjicholson** [comment]
:ok: :shipit:

One last question, does this become a general purpose "elasticsearch" helpers library or what. Right now there's only this bulk records manager, but do you have ideas for some other ones?

**Comment by cberube** [comment]
@nackjicholson -- I figure there will be others -- don't know what yet.

**Comment by notxt** [comment]
:+1:

**Pull request merged**
